---
# Service 1: Spring Boot Hello World (NodePort 30080)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello-world
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-hello-world
  template:
    metadata:
      labels:
        app: spring-hello-world
    spec:
      containers:
        - name: spring-hello-world
          imagePullPolicy: Never
          image: anji-spring-hello-world:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-hello-world-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: spring-hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # First service
---
# Service 2: Another Application (NodePort 30090)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: another-app
  template:
    metadata:
      labels:
        app: another-app
    spec:
      containers:
        - name: another-app
          image: another-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: another-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: another-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090  # Second service - different port
---

