---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-hello-world
  template:
    metadata:
      labels:
        app: spring-hello-world
    spec:
      containers:
        - name: spring-hello-world
          imagePullPolicy: Never
          image: anji-spring-hello-world:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-nodeport
spec:
  type: NodePort
  selector:
    app: spring-hello-world
  ports:
    - protocol: TCP
      port: 8080       # Cluster internal port
      targetPort: 8080 # Container port
      nodePort: 30080  # External port