---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello-world
  labels:
    app: spring-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-hello-world
  template:
    metadata:
      labels:
        app: spring-hello-world
    spec:
      containers:
      # Spring Boot Application Container
      - name: spring-hello-world
        imagePullPolicy: Never
        image: anji-spring-hello-world:anjibabu
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://localhost:3306/springdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "rootpassword"
        # Startup probe - allows Spring Boot time to start and connect to MySQL
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30  # Give up to 150 seconds for startup
        # Health checks
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      
      # MySQL Sidecar Container
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "springdb"
        - name: MYSQL_USER
          value: "springuser"
        - name: MYSQL_PASSWORD
          value: "springpassword"
        # Volume mount for MySQL data persistence
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        # Health check for MySQL
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -h localhost -u root -prootpassword"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -h localhost -u root -prootpassword"
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      
      # Volume for MySQL data persistence
      volumes:
      - name: mysql-data
        emptyDir: {}  # For development - use PersistentVolumeClaim for production
---
apiVersion: v1
kind: Service
metadata:
  name: spring-nodeport
  labels:
    app: spring-hello-world
spec:
  type: NodePort
  selector:
    app: spring-hello-world
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http

